### ISSUE TITLE
Some changes to comfyui cause `Latent-Modifiers` to work very poorly

### ISSUE THREAD

**Issue by mijuku233** [Clybius/ComfyUI-Latent-Modifiers#2]
Some recent changes to `comfyui` have caused the effect of using the `Latent-Modifier` to be poorly

This custom node is great, it became an integral part of my workflow, please fix it!

**Comment by Clybius** [comment]
Thanks for reporting this issue!

I believe it's due to commit [1777b54](https://github.com/comfyanonymous/ComfyUI/commit/1777b54d0217e77a6a64b0a587b9b11a48e3bf02)

I'll take a look into this immediately. In the meantime, could you send me your node settings for the image shown so I can attempt to replicate this locally?

EDIT:
It appears quite a few functions are broken, I'll see what I can do

**Comment by mijuku233** [comment]
@Clybius 
This is my workflow: 
[latentmodifier.json](https://github.com/Clybius/ComfyUI-Latent-Modifiers/files/13232796/latentmodifier.json)

**Comment by mijuku233** [comment]
@Clybius 
This update https://github.com/comfyanonymous/ComfyUI/commit/d2e27b48f169b0e5def6b9b2c7874e4010282921 fixes the effect of `sharpness`, but there is still a problem with `contrast`!

**Comment by Clybius** [comment]
Thanks for the update on it!

I can't seem to replicate the old contrast function *exactly* after the recent commits, even after tuning around a bit.

I will still push a commit within the next 24 hours or so for an update. It'll have a fix for contrast (should be in a good usable state after that), as well as some new functions.

**Comment by Clybius** [comment]
Pushed the changes, feel free to let me know on if there's further issues (I expect there to be some small bugs leftover, but most important functions are somewhat fixed)

**Comment by mijuku233** [comment]
@Clybius 
thank you for the update
But the `contrast` effect is still incorrect.
![ComfyUI_temp_gtrmm_00005_](https://github.com/Clybius/ComfyUI-Latent-Modifiers/assets/89350747/5d5dd161-6072-4697-ba94-5af264616101)
![ComfyUI_temp_gtrmm_00004_](https://github.com/Clybius/ComfyUI-Latent-Modifiers/assets/89350747/02d23e6b-2a72-4a5e-8c11-9aea4c77bfaa)

**Comment by mijuku233** [comment]
@Clybius 
Thanks for the update, the 'contrast' works great now, but there is a new problem with the update.
Previously, I found that setting 'sharpness' to a negative number made the resulting image softer, which was a great effect, but the latest update makes this no longer work.
Default：
![a](https://github.com/Clybius/ComfyUI-Latent-Modifiers/assets/89350747/1190a49f-d71a-4edf-a0c5-e746083ee34f)
Sharpness -60：
![b](https://github.com/Clybius/ComfyUI-Latent-Modifiers/assets/89350747/90244075-8428-441c-88b3-0ec8c5cedb37)
Sharpness -60 + Contrast 60：
![c](https://github.com/Clybius/ComfyUI-Latent-Modifiers/assets/89350747/6f1e1a91-4b79-4a69-bf68-7b2905d8e0c2)

**Comment by mijuku233** [comment]
The problem is basically solved now, fantastic, thanks again!
